name: cerberus
channels:
  - conda-forge
  - defaults
dependencies:
  - docopt=0.6.2=py37h06a4308_0
  - hdf5=1.12.1=nompi_h2386368_104
  - joblib=1.1.0=pyhd3eb1b0_0
  - matplotlib=3.5.1=py37h06a4308_1
  - matplotlib-base=3.5.1=py37ha18d171_1
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openslide
  - pandas=1.3.5=py37h8c16a72_0
  - pillow=9.0.1=py37h22f2fdc_0
  - pip=21.2.2=py37h06a4308_0
  - progress=1.5=py37h06a4308_0
  - python=3.7.12=hb7a2778_100_cpython
  - pyyaml=6.0=py37h7f8727e_1
  - scikit-image=0.19.2=py37h51133e4_0
  - scikit-learn=1.0.2=py37h51133e4_1
  - scipy=1.7.3=py37hf2a6cf1_0
  - shapely=1.7.1=py37h1728cc4_0
  - termcolor=1.1.0=py37h06a4308_1
  - tqdm=4.64.0=py37h06a4308_0
  - yaml=0.2.5=h7b6447c_0
  - pip:
    - imgaug==0.4.0
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.5.64
    - openslide-python==1.1.2
    - seaborn==0.11.2
    - tensorboardx==2.5.1
    - tiatoolbox==1.3.1
